import prisma from '../src/config/database.js';

const items = [
  {
    nome: 'Copo descartável 200ml',
    codigo: 'CD-200ML',
    categoria: 'Copa',
    unidade: 'Un',
    quantidade: 2400,
    estoqueMinimo: 0,
    estoqueMaximo: 10000,
    localizacao: '2º Andar',
    descricao: '24 pacotes com 100 unidades cada',
    ativo: true,
  },
  {
    nome: 'Touca descartável TNT',
    codigo: 'TOUCA-TNT',
    categoria: 'Copa',
    unidade: 'Un',
    quantidade: 700,
    estoqueMinimo: 0,
    estoqueMaximo: 10000,
    localizacao: '2º Andar',
    descricao: '7 pacotes com 100 unidades cada',
    ativo: true,
  },
  {
    nome: 'Luva Latex',
    codigo: 'LUVA-LATEX',
    categoria: 'Copa',
    unidade: 'Un',
    quantidade: 600,
    estoqueMinimo: 0,
    estoqueMaximo: 10000,
    localizacao: '2º Andar',
    descricao: '6 caixas com 100 unidades cada',
    ativo: true,
  },
  {
    nome: 'Guardanapo',
    codigo: 'GUARDANAPO',
    categoria: 'Copa',
    unidade: 'Un',
    quantidade: 900,
    estoqueMinimo: 0,
    estoqueMaximo: 10000,
    localizacao: '2º Andar',
    descricao: '18 pacotes com 50 unidades cada',
    ativo: true,
  },
  {
    nome: 'Copo descartável 80ml',
    codigo: 'CD-80ML',
    categoria: 'Copa',
    unidade: 'Un',
    quantidade: 2630,
    estoqueMinimo: 0,
    estoqueMaximo: 10000,
    localizacao: '2º Andar',
    descricao: '26 pacotes com 100 unidades cada + caixa fechada com 30 pacotes',
    ativo: true,
  },
  {
    nome: 'Açúcar cristal em sachê 50g',
    codigo: 'ACUCAR-SACHE-50G',
    categoria: 'Copa',
    unidade: 'Un',
    quantidade: 100,
    estoqueMinimo: 0,
    estoqueMaximo: 10000,
    localizacao: '2º Andar',
    descricao: '1 caixa com 100 unidades',
    ativo: true,
  },
  {
    nome: 'Café em pó 500g',
    codigo: 'CAFE-500G',
    categoria: 'Copa',
    unidade: 'Un',
    quantidade: 24,
    estoqueMinimo: 0,
    estoqueMaximo: 10000,
    localizacao: 'Térreo',
    descricao: '24 pacotes',
    ativo: true,
  },
  {
    nome: 'Adoçante 200ml',
    codigo: 'ADOÇANTE-200ML',
    categoria: 'Copa',
    unidade: 'Un',
    quantidade: 4,
    estoqueMinimo: 0,
    estoqueMaximo: 10000,
    localizacao: 'Térreo',
    descricao: '4 pacotes',
    ativo: true,
  },
  {
    nome: 'Sabonete líquido 5L',
    codigo: 'SABONETE-LIQ-5L',
    categoria: 'Higiene',
    unidade: 'Un',
    quantidade: 7,
    estoqueMinimo: 0,
    estoqueMaximo: 10000,
    localizacao: '2º Andar',
    descricao: '7 unidades',
    ativo: true,
  },
  {
    nome: 'Álcool gel 70° 500g',
    codigo: 'ALCOOL-GEL-500G',
    categoria: 'Higiene',
    unidade: 'Un',
    quantidade: 8,
    estoqueMinimo: 0,
    estoqueMaximo: 10000,
    localizacao: '2º Andar',
    descricao: '8 unidades',
    ativo: true,
  },
  {
    nome: 'Papel Higiênico 300m',
    codigo: 'PAPEL-HIG-300M',
    categoria: 'Higiene',
    unidade: 'Un',
    quantidade: 136,
    estoqueMinimo: 0,
    estoqueMaximo: 10000,
    localizacao: '2º Andar',
    descricao: '17 fardos com 8 rolos cada',
    ativo: true,
  },
  {
    nome: 'Papel Toalha 20cm x 200m',
    codigo: 'PAPEL-TOALHA-20X200',
    categoria: 'Higiene',
    unidade: 'Un',
    quantidade: 18,
    estoqueMinimo: 0,
    estoqueMaximo: 10000,
    localizacao: 'Térreo',
    descricao: '3 pacotes com 6 unidades cada',
    ativo: true,
  },
  {
    nome: 'Sabonete barra 1kg',
    codigo: 'SABONETE-BARRA-1KG',
    categoria: 'Limpeza',
    unidade: 'Un',
    quantidade: 35,
    estoqueMinimo: 0,
    estoqueMaximo: 10000,
    localizacao: '2º Andar',
    descricao: '7 pacotes com 5 unidades cada',
    ativo: true,
  },
  {
    nome: 'Limpa Vidro 500ml',
    codigo: 'LIMPA-VIDRO-500ML',
    categoria: 'Limpeza',
    unidade: 'Un',
    quantidade: 6,
    estoqueMinimo: 0,
    estoqueMaximo: 10000,
    localizacao: '2º Andar',
    descricao: '6 unidades',
    ativo: true,
  },
  {
    nome: 'Limpa alumínio 500ml',
    codigo: 'LIMPA-ALUMINIO-500ML',
    categoria: 'Limpeza',
    unidade: 'Un',
    quantidade: 3,
    estoqueMinimo: 0,
    estoqueMaximo: 10000,
    localizacao: '2º Andar',
    descricao: '3 unidades',
    ativo: true,
  },
  {
    nome: 'Saponáceo 300ml',
    codigo: 'SAPONACE-300ML',
    categoria: 'Limpeza',
    unidade: 'Un',
    quantidade: 1,
    estoqueMinimo: 0,
    estoqueMaximo: 10000,
    localizacao: '2º Andar',
    descricao: '1 unidade',
    ativo: true,
  },
  {
    nome: 'Lustra Móveis 200ml',
    codigo: 'LUSTRA-MOVEIS-200ML',
    categoria: 'Limpeza',
    unidade: 'Un',
    quantidade: 4,
    estoqueMinimo: 0,
    estoqueMaximo: 10000,
    localizacao: '2º Andar',
    descricao: '4 unidades',
    ativo: true,
  },
  {
    nome: 'Multiuso (Veja)',
    codigo: 'MULTIUSO-VEJA',
    categoria: 'Limpeza',
    unidade: 'Un',
    quantidade: 1,
    estoqueMinimo: 0,
    estoqueMaximo: 10000,
    localizacao: '2º Andar',
    descricao: '1 unidade',
    ativo: true,
  },
  {
    nome: 'Limpa Porcelanato 2L',
    codigo: 'LIMPA-PORCELANATO-2L',
    categoria: 'Limpeza',
    unidade: 'Un',
    quantidade: 7,
    estoqueMinimo: 0,
    estoqueMaximo: 10000,
    localizacao: '2º Andar',
    descricao: '7 unidades',
    ativo: true,
  },
  {
    nome: 'Álcool líquido 70° 5L',
    codigo: 'ALCOOL-LIQ-5L',
    categoria: 'Limpeza',
    unidade: 'Un',
    quantidade: 5,
    estoqueMinimo: 0,
    estoqueMaximo: 10000,
    localizacao: '2º Andar',
    descricao: '5 unidades',
    ativo: true,
  },
  {
    nome: 'Saco de lixo 200L',
    codigo: 'SACO-LIXO-200L',
    categoria: 'Limpeza',
    unidade: 'Un',
    quantidade: 400,
    estoqueMinimo: 0,
    estoqueMaximo: 10000,
    localizacao: '2º Andar',
    descricao: '4 pacotes com 100 unidades cada',
    ativo: true,
  },
  {
    nome: 'Saco de 60L',
    codigo: 'SACO-60L',
    categoria: 'Limpeza',
    unidade: 'Un',
    quantidade: 20,
    estoqueMinimo: 0,
    estoqueMaximo: 10000,
    localizacao: '2º Andar',
    descricao: '2 fardos com 10 pacotes cada',
    ativo: true,
  },
  {
    nome: 'Saco Alvejado (saco de chão)',
    codigo: 'SACO-ALVEJADO',
    categoria: 'Limpeza',
    unidade: 'Un',
    quantidade: 30,
    estoqueMinimo: 0,
    estoqueMaximo: 10000,
    localizacao: '2º Andar',
    descricao: '3 pacotes com 10 unidades cada',
    ativo: true,
  },
  {
    nome: 'Flanela M',
    codigo: 'FLANELA-M',
    categoria: 'Limpeza',
    unidade: 'Un',
    quantidade: 36,
    estoqueMinimo: 0,
    estoqueMaximo: 10000,
    localizacao: '2º Andar',
    descricao: '3 pacotes com 12 unidades cada',
    ativo: true,
  },
];

const main = async () => {
  for (const item of items) {
    const exists = await prisma.produto.findUnique({ where: { codigo: item.codigo } });
    if (exists) {
      console.log('Já existe:', item.nome, '-', item.codigo);
      continue;
    }
    await prisma.produto.create({ data: item });
    console.log('Inserido:', item.nome, '-', item.codigo);
  }
  await prisma.$disconnect();
};

main().catch(async (err) => {
  console.error(err);
  await prisma.$disconnect();
  process.exit(1);
});